AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kinesis_event_consumer_function

  Sample SAM Template for kinesis-consumer-with-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  LambdaKinesisConsumerJavaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: java-kinesis-consumer-dynamodb-sam
      CodeUri: kinesis_event_consumer_function
      Handler: com.amazonaws.services.lambda.samples.events.kinesis.HandlerKinesis::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_DB_TABLE: !Ref KinesisDynamoDBTable
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt KinesisStream.Arn
            BatchSize: 10
            StartingPosition: LATEST
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures
            MaximumBatchingWindowInSeconds: 300
            MaximumRecordAgeInSeconds: 7200
            MaximumRetryAttempts: 10
            
      Policies:
      - Statement:
        - Sid: DynamoDBPermissionsPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          - dynamodb:ConditionCheckItem
          Resource: 
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref KinesisDynamoDBTable]]
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref KinesisDynamoDBTable, "/index/*"]]

  KinesisDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: KinesisDynamoDBTableJava
      PrimaryKey:
        Name: PartitionKey
        Type: String 
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref KinesisStreamName
      ShardCount: 4
      StreamModeDetails:
        StreamMode: PROVISIONED
Parameters:  
  KinesisStreamName:
    Type: String
    Description: Enter the name of the Kinesis Data Stream
Outputs:
  LambdaKinesisConsumerJavaFunction:
    Description: "Kinesis Stream Consumer Lambda Function ARN"
    Value: !GetAtt LambdaKinesisConsumerJavaFunction.Arn
