AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sns_event_consumer_function

  Sample SAM Template for sns-consumer-with-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  LambdaSNSConsumerJavaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: java-sns-consumer-dynamodb-sam
      CodeUri: sns_event_consumer_function
      Handler: com.amazonaws.services.lambda.samples.events.sns.HandlerSNS::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_DB_TABLE: !Ref SNSDynamoDBTable
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref LambdaSNSTopic
      Policies:
      - Statement:
        - Sid: DynamoDBPermissionsPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          - dynamodb:ConditionCheckItem
          Resource: 
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref SNSDynamoDBTable]]
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref SNSDynamoDBTable, "/index/*"]]
  TopicConsumerFunction1Permission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref LambdaSNSConsumerJavaFunction
      Principal: sns.amazonaws.com
  SNSDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: SNSDynamoDBTableJava
      PrimaryKey:
        Name: MessageID
        Type: String 
  LambdaSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref SNSTopicName
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt LambdaSNSConsumerJavaFunction.Arn
Parameters:  
  SNSTopicName:
    Type: String
    Description: Enter the name of the SNS Topic
Outputs:
  LambdaSNSConsumerJavaFunction:
    Description: "Topic Consumer Lambda Function ARN"
    Value: !GetAtt LambdaSNSConsumerJavaFunction.Arn
