AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dynamodb_streams_event_consumer_function

  Sample SAM Template for dynamodb-streams-consumer-with-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  LambdaDynamoDBStreamsConsumerJavaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: java-dynamodb-streams-consumer-dynamodb-sam
      CodeUri: dynamodb_streams_event_consumer_function
      Handler: com.amazonaws.services.lambda.samples.events.dynamodbstreams.HandlerDynamoDBStreams::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_DB_TABLE: !Ref StreamsConsumerDynamoDBTable
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Enabled: true
            Stream: !GetAtt StreamsProducerDynamoDBTable.StreamArn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 300
            StartingPosition: TRIM_HORIZON
      Policies:
      - AWSLambdaDynamoDBExecutionRole
      - Statement:
        - Sid: DynamoDBPermissionsPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          - dynamodb:ConditionCheckItem
          Resource: 
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref StreamsConsumerDynamoDBTable]]
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref StreamsConsumerDynamoDBTable, "/index/*"]]

  StreamsConsumerDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: DynamoDBStreamsConsumerDynamoDBTableJava
      PrimaryKey:
        Name: MessageID
        Type: String 
  StreamsProducerDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: MessageID
          AttributeType: S
      KeySchema: 
        - AttributeName: MessageID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName: !Ref ProducerDynamoDBTable
      TimeToLiveSpecification:
        AttributeName: TimeToLive
        Enabled: true
Parameters:  
  ProducerDynamoDBTable:
    Type: String
    Description: Enter the name of the DynamoDB Table with Streams Enabled
Outputs:
  LambdaDynamoDBStreamsConsumerJavaFunction:
    Description: "DynamoDB Streams Consumer Lambda Function ARN"
    Value: !GetAtt LambdaDynamoDBStreamsConsumerJavaFunction.Arn
