version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-java-lambda-msk"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o3lfpmnghetp"
s3_prefix = "sam-java-lambda-msk"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MSKClusterName=\"MSKWorkshopCluster\" MSKClusterId=\"a93759a9-c9d0-4952-984c-492c6bfa2be8-13\" MSKTopic=\"MskIamTestTopic\""
image_repositories = []
