AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sqs_fifo_event_consumer_function

  Sample SAM Template for sqs-fifo-consumer-with-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  LambdaSQSFIFOConsumerJavaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: java-sqs-fifo-consumer-dynamodb-sam
      CodeUri: sqs_fifo_event_consumer_function
      Handler: com.amazonaws.services.lambda.samples.events.sqs.fifo.HandlerSQSFIFO::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_DB_TABLE: !Ref SQSFIFODynamoDBTable
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        SQSFIFOEvent:
          Type: SQS
          Properties:
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures
            Queue: !GetAtt FifoSqsQueue.Arn
            BatchSize: 10
      Policies:
      - Statement:
        - Sid: DynamoDBPermissionsPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          - dynamodb:ConditionCheckItem
          Resource: 
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref SQSFIFODynamoDBTable]]
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref SQSFIFODynamoDBTable, "/index/*"]]

  SQSFIFODynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: SQSFIFODynamoDBTableJava
      PrimaryKey:
        Name: MessageID
        Type: String 
  FifoSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
        QueueName: !Join ["", [!Ref SQSFIFOQueueName, ".fifo"]]
        MessageRetentionPeriod: 3600
        FifoQueue: true
Parameters:  
  SQSFIFOQueueName:
    Type: String
    Description: Enter the name of the SQS FIFO Queue (do not include .fifo at the end)
Outputs:
  LambdaSQSFIFOConsumerJavaFunction:
    Description: "Queue Consumer Lambda Function ARN"
    Value: !GetAtt LambdaSQSFIFOConsumerJavaFunction.Arn
