AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sqs_event_consumer_function

  Sample SAM Template for sqs-consumer-with-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  LambdaSQSConsumerJavaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: java-sqs-consumer-dynamodb-sam
      CodeUri: sqs_event_consumer_function
      Handler: com.amazonaws.services.lambda.samples.events.sqs.HandlerSQS::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_DB_TABLE: !Ref SQSDynamoDBTable
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 300
            
      Policies:
      - Statement:
        - Sid: DynamoDBPermissionsPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          - dynamodb:ConditionCheckItem
          Resource: 
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref SQSDynamoDBTable]]
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref SQSDynamoDBTable, "/index/*"]]

  SQSDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: SQSDynamoDBTableJava
      PrimaryKey:
        Name: MessageID
        Type: String 
  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
        QueueName: !Ref SQSQueueName
        MessageRetentionPeriod: 3600
Parameters:  
  SQSQueueName:
    Type: String
    Description: Enter the name of the SQS Queue
Outputs:
  LambdaSQSConsumerJavaFunction:
    Description: "Queue Consumer Lambda Function ARN"
    Value: !GetAtt LambdaSQSConsumerJavaFunction.Arn
