AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sns_fifo_event_consumer_function

  Sample SAM Template for sns-fifo-consumer-with-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
Resources:
  LambdaSNSFIFOConsumerJavaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: java-sns-fifo-consumer-dynamodb-sam
      CodeUri: sqs_fifo_event_consumer_function
      Handler: com.amazonaws.services.lambda.samples.events.sqs.fifo.HandlerSQSFIFO::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_DB_TABLE: !Ref SNSFIFODynamoDBTable
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        SQSFIFOEvent:
          Type: SQS
          Properties:
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures
            Queue: !GetAtt FifoSqsQueue.Arn
            BatchSize: 10
      Policies:
      - Statement:
        - Sid: DynamoDBPermissionsPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          - dynamodb:ConditionCheckItem
          Resource: 
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref SNSFIFODynamoDBTable]]
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref SNSFIFODynamoDBTable, "/index/*"]]
  SNSFIFODynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: SNSFIFODynamoDBTableJava
      PrimaryKey:
        Name: MessageID
        Type: String 
  LambdaSNSFIFOTopic:
    Type: AWS::SNS::Topic
    Properties:
      FifoTopic: true
      TopicName: !Join ["", [!Ref SNSFIFOTopicName, ".fifo"]]
  FifoSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
        QueueName: !Join ["", [!Ref SQSFIFOQueueName, ".fifo"]]
        MessageRetentionPeriod: 3600
        FifoQueue: true
  SNSTopicToSQSQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn: !Ref LambdaSNSFIFOTopic
      Endpoint: !GetAtt FifoSqsQueue.Arn
  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref FifoSqsQueue
      PolicyDocument:
        Id: AllowSendMessage
        Statement:
          - Sid: PermissionsWithinAccount
            Effect: Allow
            Principal:
              AWS:
                - !Ref AWS::AccountId
            Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
            Resource:
              - !GetAtt FifoSqsQueue.Arn
          - Sid: AllowSNSTopicToSendMessage
            Effect: Allow
            Principal: '*'
            Action:
              - sqs:SendMessage
            Resource:
              - !GetAtt FifoSqsQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref LambdaSNSFIFOTopic
Parameters:  
  SNSFIFOTopicName:
    Type: String
    Description: Enter the name of the SNS Topic (do not include the .fifo at the end)
  SQSFIFOQueueName:
    Type: String
    Description: Enter the name of the SQS FIFO Queue (do not include .fifo at the end)
Outputs:
  LambdaSNSFIFOConsumerJavaFunction:
    Description: "Topic Consumer Lambda Function ARN"
    Value: !GetAtt LambdaSNSFIFOConsumerJavaFunction.Arn
