AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eventbridge_event_consumer_function

  Sample SAM Template for eventbridge-consumer-with-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  LambdaEventbridgeConsumerJavaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: java-eventbridge-consumer-dynamodb-sam
      CodeUri: eventbridge_event_consumer_function
      Handler: com.amazonaws.services.lambda.samples.events.eventbridge.HandlerEventbridge::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DYNAMO_DB_TABLE: !Ref EventbridgeDynamoDBTable
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
      - Statement:
        - Sid: DynamoDBPermissionsPolicy
          Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
          - dynamodb:PutItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          - dynamodb:ConditionCheckItem
          Resource: 
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref EventbridgeDynamoDBTable]]
          - !Join ['', ["arn:", "aws:", "dynamodb:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", "table/", !Ref EventbridgeDynamoDBTable, "/index/*"]]
  PermissionForEventsToInvokeLambda:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref LambdaEventbridgeConsumerJavaFunction
      Principal: events.amazonaws.com
      SourceArn: 
        Fn::GetAtt: 
          - "EventbridgeEventLambdaRule"
          - "Arn"
  EventbridgeDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: EventbridgeDynamoDBTableJava
      PrimaryKey:
        Name: MessageID
        Type: String 
  EventbridgeEventLambdaRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref EventBusName
      EventPattern:
        account:
          - !Ref "AWS::AccountId"
      Name: eventbridge-event-lambda-rule
      State: ENABLED
      Targets:
        - 
          Arn: 
            Fn::GetAtt: 
              - "LambdaEventbridgeConsumerJavaFunction"
              - "Arn"
          Id: "eventbridge-event-lambda-rule-lambda-target"
Parameters:  
  EventBusName:
    Type: String
    Description: Enter the name of the Eventbridge Bus
Outputs:
  LambdaEventbridgeConsumerJavaFunction:
    Description: "Topic Consumer Lambda Function ARN"
    Value: !GetAtt LambdaEventbridgeConsumerJavaFunction.Arn
